rule [
    ruleID "3HP4HB_carboxylation_acetyl-CoA_carboxylase_01"
    labelType "term"
    left [
        edge [ source 0 target 2 label "-" ]
        edge [ source 8 target 10 label "-" ]
        edge [ source 11 target 12 label "-" ]
        edge [ source 13 target 14 label "-" ]
        node [ id 10 label "O-" ]
        node [ id 23 label "H+" ] 
    ]
    context [
        node [ id 0 label "C" ]
        node [ id 1 label "_X" ]
        node [ id 2 label "H" ]
        node [ id 3 label "H" ]
        node [ id 4 label "C" ]
        node [ id 5 label "O" ]
        node [ id 6 label "S" ]
        node [ id 7 label "CoA" ]
        node [ id 8 label "C" ]
        node [ id 9 label "O" ]
        node [ id 11 label "O" ]
        node [ id 12 label "H" ]
        node [ id 13 label "P" ]
        node [ id 14 label "O" ] 
        node [ id 15 label "P" ]
        node [ id 16 label "O" ]
        node [ id 17 label "P" ]
        node [ id 18 label "O" ] 
        node [ id 19 label "O" ] 
        node [ id 20 label "H" ] 
        node [ id 21 label "O" ] 
        node [ id 22 label "H" ]         
        edge [ source 0 target 1 label "-" ]
        edge [ source 0 target 3 label "-" ]
        edge [ source 0 target 4 label "-" ]
        edge [ source 4 target 5 label "=" ]
        edge [ source 4 target 6 label "-" ]
        edge [ source 6 target 7 label "-" ]
        edge [ source 8 target 9 label "=" ]
        edge [ source 8 target 11 label "-" ]
        edge [ source 14 target 15 label "-" ]
        edge [ source 15 target 16 label "-" ]
        edge [ source 16 target 17 label "-" ]
        edge [ source 13 target 18 label "=" ]
        edge [ source 13 target 21 label "-" ]
        edge [ source 21 target 22 label "-" ]
        edge [ source 13 target 19 label "-" ]
        edge [ source 19 target 20 label "-" ]
    ]
    right [
        edge [ source 0 target 8 label "-" ]
        edge [ source 2 target 11 label "-" ]
        edge [ source 10 target 12 label "-" ]
        edge [ source 10 target 13 label "-" ]
        edge [ source 14 target 23 label "-" ]
        node [ id 10 label "O" ]
        node [ id 23 label "H" ]
    ]
    constrainLabelAny [
        label "_X"
        labels [ label "C" label "H" ]
    ]
]