rule [
    ruleID "3HP4HB_activation_4HBCoA_synthetase_01"
    labelType "term"
    left [
        edge [ source 0 target 3 label "-" ]
        edge [ source 8 target 10 label "-" ]
        edge [ source 13 target 14 label "-" ]
    ]
    context [
        node [ id 0 label "C" ]
        node [ id 1 label "O" ]
        node [ id 2 label "C" ]
        node [ id 3 label "O" ]
        node [ id 4 label "H" ]
        node [ id 5 label "_X" ]
        node [ id 6 label "H" ]
        node [ id 7 label "H" ]
        node [ id 8 label "S" ]
        node [ id 9 label "CoA" ]
        node [ id 10 label "H" ]
        node [ id 11 label "_Y" ]
        node [ id 12 label "O" ]
        node [ id 13 label "P" ]
        node [ id 14 label "O" ]
        node [ id 15 label "P" ]
        node [ id 16 label "O" ]
        node [ id 17 label "O" ]
        node [ id 18 label "H" ]
        node [ id 19 label "O" ]
        node [ id 20 label "O" ]
        node [ id 21 label "H" ]
        node [ id 22 label "O" ]
        node [ id 23 label "_Z" ]        
        edge [ source 0 target 1 label "=" ]
        edge [ source 0 target 2 label "-" ]
        edge [ source 2 target 4 label "-" ]
        edge [ source 2 target 5 label "-" ]
        edge [ source 2 target 6 label "-" ]
        edge [ source 3 target 7 label "-" ]
        edge [ source 8 target 9 label "-" ]
        edge [ source 11 target 12 label "-" ]
        edge [ source 12 target 13 label "-" ]
        edge [ source 14 target 15 label "-" ]
        edge [ source 13 target 16 label "=" ]
        edge [ source 13 target 17 label "-" ]
        edge [ source 17 target 18 label "-" ]
        edge [ source 15 target 19 label "=" ]
        edge [ source 15 target 20 label "-" ]
        edge [ source 20 target 21 label "-" ]
        edge [ source 15 target 22 label "-" ]    
        edge [ source 22 target 23 label "-" ]    
    ]
    right [
        edge [ source 0 target 8 label "-" ]
        edge [ source 3 target 13 label "-" ]
        edge [ source 10 target 14 label "-" ]
    ]
    constrainLabelAny [
        label "_X"
        labels [label "C" ]
    ]
    constrainLabelAny [
        label "_Y"
        labels [label "H" label "P" ]
    ]
    constrainLabelAny [
        label "_Z"
        labels [label "P" label "Ad" ]
    ]
]