rule [
    ruleID "3HP4HB_transferase_acetyl-CoA_C-acyltransferase_01"
    labelType "term"
    left [
        edge [ source 0 target 2 label "-" ]
        edge [ source 13 target 14 label "-" ]
    ]
    context [
        node [ id 0 label "C" ]
        node [ id 1 label "H" ]
        node [ id 2 label "C" ]
        node [ id 3 label "H" ]
        node [ id 4 label "C" ]
        node [ id 5 label "O" ]
        node [ id 6 label "C" ]
        node [ id 7 label "H" ]
        node [ id 8 label "H" ]
        node [ id 9 label "H" ]
        node [ id 10 label "O" ]
        node [ id 11 label "S" ]
        node [ id 12 label "CoA" ]
        node [ id 13 label "H" ]
        node [ id 14 label "S" ]
        node [ id 15 label "CoA" ]
        edge [ source 0 target 1 label "-" ]
        edge [ source 0 target 3 label "-" ]
        edge [ source 0 target 4 label "-" ]
        edge [ source 2 target 5 label "=" ]
        edge [ source 2 target 6 label "-" ]
        edge [ source 6 target 7 label "-" ]
        edge [ source 6 target 8 label "-" ]
        edge [ source 6 target 9 label "-" ]
        edge [ source 4 target 10 label "=" ]
        edge [ source 4 target 11 label "-" ]
        edge [ source 11 target 12 label "-" ]
        edge [ source 14 target 15 label "-" ]        
    ]
    right [
        edge [ source 0 target 13 label "-" ]
        edge [ source 2 target 14 label "-" ]
    ]
]