rule[
    ruleID "3HPbicy_transferase_succinyl-CoA_malate-CoA_transferase_01"
    labelType "term"
    left [
        edge [ source 0 target 2 label "-" ]
        edge [ source 8 target 11 label "-" ]
    ]
    context [
        node [ id 0 label "C" ]
        node [ id 1 label "O" ]
        node [ id 2 label "S" ]
        node [ id 3 label "C" ]
        node [ id 4 label "CoA" ]
        node [ id 5 label "H" ]
        node [ id 6 label "H" ]
        node [ id 7 label "_X" ]
        node [ id 8 label "C" ]
        node [ id 9 label "C" ]
        node [ id 10 label "O" ]
        node [ id 11 label "O" ]
        node [ id 12 label "H" ]
        node [ id 13 label "H" ]
        node [ id 14 label "H" ]
        node [ id 15 label "C" ]
        node [ id 16 label "_Y" ]
        node [ id 17 label "O" ]
        node [ id 18 label "H" ]
        node [ id 19 label "H" ]
        edge [ source 0 target 1 label "=" ]
        edge [ source 0 target 3 label "-" ]
        edge [ source 3 target 5 label "-" ]
        edge [ source 3 target 6 label "-" ]
        edge [ source 3 target 7 label "-" ]
        edge [ source 2 target 4 label "-" ]
        edge [ source 8 target 9 label "-" ]
        edge [ source 8 target 10 label "=" ]
        edge [ source 11 target 12 label "-" ]
        edge [ source 9 target 13 label "-" ]
        edge [ source 9 target 14 label "-" ]
        edge [ source 9 target 15 label "-" ]
        edge [ source 15 target 16 label "-" ]
        edge [ source 15 target 17 label "-" ]
        edge [ source 15 target 19 label "-" ]
        edge [ source 17 target 18 label "-" ]
    ]
    right [
        edge [ source 0 target 11 label "-" ]
        edge [ source 2 target 8 label "-" ]        
    ]
    constrainLabelAny [
        label "_X"
        labels [ label "C" ]        
    ]
    constrainLabelAny [
        label "_Y"
        labels [ label "C" ]        
    ]
]