rule [
    ruleID "3HPbicy_mesaconyl_C1_C4_CoA_transferase_01"
    labelType "term"
    left [
        edge [ source 0 target 1 label "-" ]
        edge [ source 4 target 5 label "-" ]
    ]
    context [
        node [ id 0 label "S" ]
        node [ id 1 label "C" ]
        node [ id 2 label "C" ]
        node [ id 3 label "C" ]
        node [ id 4 label "C" ]
        node [ id 5 label "O" ]
        node [ id 6 label "O" ]
        node [ id 7 label "H" ]
        node [ id 8 label "O" ]
        node [ id 9 label "CoA" ]
        node [ id 10 label "C" ]
        node [ id 11 label "H" ]
        node [ id 12 label "H" ]
        node [ id 13 label "H" ]
        node [ id 14 label "H" ]        
        edge [ source 0 target 9 label "-" ]
        edge [ source 1 target 6 label "=" ]
        edge [ source 1 target 2 label "-" ]
        edge [ source 2 target 3 label "=" ]
        edge [ source 2 target 10 label "-" ]
        edge [ source 10 target 11 label "-" ]
        edge [ source 10 target 12 label "-" ]
        edge [ source 10 target 13 label "-" ]
        edge [ source 3 target 7 label "-" ]
        edge [ source 3 target 4 label "-" ]
        edge [ source 4 target 8 label "=" ]
        edge [ source 5 target 14 label "-" ]
    ]
    right [
        edge [ source 1 target 5 label "-" ]
        edge [ source 4 target 0 label "-" ]        
    ]
]