rule [
    ruleID "CBB_activation_s1,7p_f1,5p_bisphosphatase_01"
    labelType "term"
    left [
        edge [ source 6 target 7 label "-" ]
        edge [ source 14 target 13 label "-" ]
    ]
    context [
        node [ id 0 label "C" ]
        node [ id 1 label "C" ]
        node [ id 2 label "C" ]
        node [ id 3 label "O" ]
        node [ id 4 label "O" ]
        node [ id 5 label "H" ]
        node [ id 6 label "O" ]
        node [ id 7 label "P" ]
        node [ id 8 label "O" ]
        node [ id 9 label "O" ]
        node [ id 10 label "H" ]
        node [ id 11 label "O" ]
        node [ id 12 label "H" ]
        node [ id 13 label "O" ]
        node [ id 14 label "H" ]
        node [ id 15 label "H" ]
        edge [ source 0 target 1 label "-" ]
        edge [ source 0 target 6 label "-" ]
        edge [ source 1 target 2 label "-" ]
        edge [ source 1 target 3 label "=" ]
        edge [ source 2 target 4 label "-" ]
        edge [ source 4 target 5 label "-" ]
        edge [ source 7 target 8 label "=" ]
        edge [ source 7 target 9 label "-" ]
        edge [ source 7 target 11 label "-" ]
        edge [ source 9 target 10 label "-" ]
        edge [ source 11 target 12 label "-" ]
        edge [ source 13 target 15 label "-" ]        
    ]
    right [
        edge [ source 6 target 14 label "-" ]
        edge [ source 7 target 13 label "-" ]
    ]
]