rule [
    ruleID "CBB_RuBisCo_carboxylation_01"
    labelType "term"
    left [
        edge [ source 1 target 2 label "-" ]
        edge [ source 1 target 7 label "=" ]
        edge [ source 2 target 8 label "-" ]
        edge [ source 2 target 10 label "-" ]
        edge [ source 8 target 9 label "-" ]
        edge [ source 15 target 17 label "=" ]
        edge [ source 18 target 20 label "-" ]
    ]
    context [
        node [ id 0 label "C" ]
        node [ id 1 label "C" ]
        node [ id 2 label "C" ]
        node [ id 3 label "C" ]
        node [ id 4 label "C" ]
        node [ id 5 label "O" ]
        node [ id 6 label "P" ]
        node [ id 7 label "O" ]
        node [ id 8 label "O" ]
        node [ id 9 label "H" ]
        node [ id 10 label "H" ]
        node [ id 11 label "O" ]
        node [ id 12 label "H" ]
        node [ id 13 label "O" ]
        node [ id 14 label "P" ]
        node [ id 15 label "C" ]
        node [ id 16 label "O" ]
        node [ id 17 label "O" ]
        node [ id 18 label "O" ]
        node [ id 19 label "H" ]
        node [ id 20 label "H" ]
        edge [ source 0 target 1 label "-" ]
        edge [ source 0 target 5 label "-" ]
        edge [ source 5 target 6 label "-" ]
        edge [ source 2 target 3 label "-" ]
        edge [ source 3 target 11 label "-" ]
        edge [ source 11 target 12 label "-" ]
        edge [ source 3 target 4 label "-" ]
        edge [ source 4 target 13 label "-" ]
        edge [ source 13 target 14 label "-" ]
        edge [ source 15 target 16 label "=" ]
        edge [ source 18 target 19 label "-" ]
    ]
    right [
        edge [ source 1 target 10 label "-" ]
        edge [ source 1 target 7 label "-" ]
        edge [ source 1 target 15 label "-" ]
        edge [ source 2 target 18 label "-" ]
        edge [ source 2 target 8 label "=" ]
        edge [ source 7 target 9 label "-" ]
        edge [ source 15 target 17 label "-" ]
        edge [ source 17 target 20 label "-" ]
    ]
]