rule [
    ruleID "CBB_ribulose-5-P_kinase_01"
    labelType "term"
    left [
        edge [ source 4 target 5 label "-" ]
        edge [ source 9 target 10 label "-" ]
    ]
    context [
        node [ id 1 label "C" ]
        node [ id 2 label "C" ]
        node [ id 3 label "C" ]
        node [ id 4 label "O" ]
        node [ id 5 label "H" ]
        node [ id 6 label "H" ]
        node [ id 7 label "H" ]
        node [ id 8 label "O" ]
        node [ id 9 label "P" ]
        node [ id 10 label "O" ]
        node [ id 11 label "P" ]
        node [ id 12 label "O" ]
        node [ id 13 label "P" ]
        node [ id 14 label "O" ]
        node [ id 15 label "Ad" ]
        node [ id 16 label "O" ]
        node [ id 17 label "O" ]
        node [ id 18 label "H" ]
        node [ id 19 label "O" ]
        node [ id 20 label "H" ]
        edge [ source 1 target 2 label "-" ]
        edge [ source 2 target 3 label "-" ]
        edge [ source 1 target 4 label "-" ]
        edge [ source 1 target 6 label "-" ]
        edge [ source 1 target 7 label "-" ]
        edge [ source 2 target 8 label "=" ]
        edge [ source 9 target 16 label "=" ]
        edge [ source 9 target 17 label "-" ]
        edge [ source 17 target 18 label "-" ]
        edge [ source 9 target 19 label "-" ]
        edge [ source 19 target 20 label "-" ]
        edge [ source 10 target 11 label "-" ]
        edge [ source 11 target 12 label "-" ]
        edge [ source 12 target 13 label "-" ]
        edge [ source 13 target 14 label "-" ]
        edge [ source 14 target 15 label "-" ]
    ]
    right [
        edge [ source 4 target 9 label "-" ]
        edge [ source 5 target 10 label "-" ]
    ]
]