rule [
    ruleID "CBB_phosphoglycerate_kinase_01"
    labelType "term"
    left [
        edge [ source 2 target 3 label "-" ]
        edge [ source 5 target 6 label "-" ]
    ]
    context [
        node [ id 0 label "C" ]
        node [ id 1 label "C" ]
        node [ id 2 label "O" ]
        node [ id 3 label "H" ]
        node [ id 4 label "O" ]
        node [ id 5 label "P" ]
        node [ id 6 label "O" ]
        node [ id 7 label "P" ]
        node [ id 8 label "O" ]
        node [ id 9 label "P" ]
        node [ id 10 label "O" ]
        node [ id 11 label "Ad" ]
        node [ id 12 label "O" ]
        node [ id 13 label "O" ]
        node [ id 14 label "H" ]
        node [ id 15 label "O" ]
        node [ id 16 label "H" ]
        edge [ source 0 target 1 label "-" ]
        edge [ source 0 target 4 label "=" ]
        edge [ source 0 target 2 label "-" ]
        edge [ source 5 target 13 label "-" ]
        edge [ source 5 target 15 label "-" ]
        edge [ source 5 target 12 label "=" ]
        edge [ source 13 target 14 label "-" ]
        edge [ source 15 target 16 label "-" ]
        edge [ source 6 target 7 label "-" ]
        edge [ source 7 target 8 label "-" ]
        edge [ source 8 target 9 label "-" ]
        edge [ source 9 target 10 label "-" ]
        edge [ source 10 target 11 label "-" ]
    ]
    right [
        edge [ source 2 target 5 label "-" ]
        edge [ source 6 target 3 label "-" ]
    ]
]