rule [
    ruleID "CBB_GAP_dehydrogenase_01"
    labelType "term"
    left [
        edge [ source 0 target 5 label "-" ]
        edge [ source 13 target 14 label "-" ]
        node [ id 14 label "NADP" ]
        node [ id 12 label "H+" ]
    ]
    context [
        node [ id 0 label "C" ]
        node [ id 1 label "C" ]
        node [ id 2 label "O" ]
        node [ id 3 label "O" ]
        node [ id 4 label "H" ]
        node [ id 5 label "O" ]
        node [ id 6 label "P" ]
        node [ id 7 label "O" ]
        node [ id 8 label "O" ]
        node [ id 9 label "H" ]
        node [ id 10 label "O" ]
        node [ id 11 label "H" ]
        node [ id 13 label "H" ]
        edge [ source 0 target 1 label "-" ]
        edge [ source 0 target 2 label "=" ]
        edge [ source 1 target 3 label "-" ]
        edge [ source 3 target 4 label "-" ]
        edge [ source 5 target 6 label "-" ]
        edge [ source 6 target 7 label "=" ]
        edge [ source 6 target 8 label "-" ]
        edge [ source 8 target 9 label "-" ]
        edge [ source 6 target 10 label "-" ]
        edge [ source 10 target 11 label "-" ]        
    ]
    right [
        edge [ source 0 target 13 label "-" ]
        edge [ source 5 target 12 label "-" ]
        node [ id 14 label "NADP+" ]
        node [ id 12 label "H" ]
    ]
]