rule [
    ruleID "CBB_transketolase_01"
    labelType "term"
    left [
        edge [ source 1 target 2 label "-" ]
        edge [ source 2 target 13 label "-" ]
        edge [ source 13 target 14 label "-" ]
        edge [ source 5 target 23 label "=" ]
        node [ id 23 label "O" ]
    ]
    context [
        node [ id 0 label "C" ]
        node [ id 1 label "C" ]
        node [ id 2 label "C" ]
        node [ id 3 label "C" ]
        node [ id 4 label "C" ]
        node [ id 5 label "C" ]
        node [ id 6 label "C" ]
        node [ id 7 label "C" ]
        node [ id 8 label "O" ]
        node [ id 9 label "H" ]
        node [ id 10 label "H" ]
        node [ id 11 label "H" ]
        node [ id 12 label "O" ]
        node [ id 13 label "O" ]
        node [ id 14 label "H" ]
        node [ id 15 label "H" ]
        node [ id 16 label "O" ]
        node [ id 17 label "H" ]
        node [ id 18 label "H" ]
        node [ id 19 label "O" ]
        node [ id 20 label "_X" ]
        node [ id 21 label "H" ]
        node [ id 22 label "_W" ]
        node [ id 24 label "H" ]
        node [ id 25 label "O" ]
        node [ id 26 label "H" ]
        node [ id 27 label "H" ]
        node [ id 28 label "O" ]
        node [ id 29 label "_Z" ]
        node [ id 30 label "H" ]
        node [ id 31 label "_Y" ]
        edge [ source 8 target 9 label "-" ]
        edge [ source 0 target 1 label "-" ]
        edge [ source 0 target 8 label "-" ]
        edge [ source 0 target 10 label "-" ]
        edge [ source 0 target 11 label "-" ]
        edge [ source 1 target 12 label "=" ]
        edge [ source 2 target 3 label "-" ]
        edge [ source 2 target 15 label "-" ]
        edge [ source 3 target 4 label "-" ]
        edge [ source 3 target 16 label "-" ]
        edge [ source 16 target 17 label "-" ]
        edge [ source 3 target 18 label "-" ]
        edge [ source 4 target 19 label "-" ]
        edge [ source 19 target 20 label "-" ]
        edge [ source 4 target 21 label "-" ]
        edge [ source 4 target 22 label "-" ]
        edge [ source 5 target 6 label "-" ]
        edge [ source 5 target 24 label "-" ]
        edge [ source 6 target 7 label "-" ]
        edge [ source 6 target 25 label "-" ]
        edge [ source 25 target 26 label "-" ]
        edge [ source 6 target 27 label "-" ]
        edge [ source 7 target 28 label "-" ]
        edge [ source 28 target 29 label "-" ]
        edge [ source 7 target 30 label "-" ]
        edge [ source 7 target 31 label "-" ]
    ]
    right [
        edge [ source 1 target 5 label "-" ]
        edge [ source 5 target 23 label "-" ]
        edge [ source 23 target 14 label "-" ]
        edge [ source 2 target 13 label "=" ]
        node [ id 23 label "xyO" ]
    ]
    constrainLabelAny [
        label "_W"
        labels [ label "H" label "C" ]        
    ]
    constrainLabelAny [
        label "_X"
        labels [ label "H" label "P" ]        
    ]
    constrainLabelAny [
        label "_Y"
        labels [ label "H" label "C" ]        
    ]
    constrainLabelAny [
        label "_Z"
        labels [ label "H" label "P" ]        
    ]
]