rule [
    ruleID "CETCH_activation_lysis_malate_synthase_02"
    labelType "term"
    left [
        edge [ source 0 target 1 label "=" ]
        edge [ source 6 target 7 label "-" ]
        edge [ source 8 target 12 label "-" ]
        edge [ source 14 target 15 label "-" ]
    ]
    context [
        node [ id 0 label "C" ]
        node [ id 1 label "O" ]
        node [ id 2 label "H" ]
        node [ id 3 label "C" ]
        node [ id 4 label "O" ]
        node [ id 5 label "O" ]
        node [ id 6 label "C" ]
        node [ id 7 label "H" ]
        node [ id 8 label "C" ]
        node [ id 9 label "H" ]
        node [ id 10 label "_X" ]
        node [ id 11 label "O" ]
        node [ id 12 label "S" ]
        node [ id 13 label "CoA" ]
        node [ id 14 label "O" ]
        node [ id 15 label "H" ]
        node [ id 16 label "H" ]
        edge [ source 0 target 2 label "-" ]
        edge [ source 0 target 3 label "-" ]
        edge [ source 3 target 4 label "=" ]
        edge [ source 3 target 5 label "-" ]
        edge [ source 6 target 8 label "-" ]
        edge [ source 6 target 9 label "-" ]
        edge [ source 6 target 10 label "-" ]
        edge [ source 8 target 11 label "=" ]
        edge [ source 12 target 13 label "-" ]
        edge [ source 14 target 16 label "-" ]
    ]
    right [
        edge [ source 0 target 1 label "-" ]
        edge [ source 0 target 6 label "-" ]
        edge [ source 1 target 7 label "-" ]
        edge [ source 8 target 14 label "-" ]
        edge [ source 12 target 15 label "-" ]
    ]
    constrainLabelAny [
        label "_X"
        labels [ label "C" label "H" ]
    ]
]