graph [
	node [ id 0 label "S" ]
	node [ id 1 label "C" ]
	node [ id 2 label "C" ]
	node [ id 3 label "N" ]
	node [ id 4 label "C" ]
	node [ id 5 label "O" ]
	node [ id 6 label "C" ]
	node [ id 7 label "C" ]
	node [ id 8 label "N" ]
	node [ id 9 label "C" ]
	node [ id 10 label "O" ]
	node [ id 11 label "C" ]
	node [ id 12 label "C" ]
	node [ id 13 label "C" ]
	node [ id 14 label "C" ]
	node [ id 15 label "C" ]
	node [ id 16 label "O" ]
	node [ id 17 label "P" ]
	node [ id 18 label "O" ]
	node [ id 19 label "O" ]
	node [ id 20 label "O" ]
	node [ id 21 label "P" ]
	node [ id 22 label "O" ]
	node [ id 23 label "O" ]
	node [ id 24 label "O" ]
	node [ id 25 label "C" ]
	node [ id 26 label "C" ]
	node [ id 27 label "C" ]
	node [ id 28 label "C" ]
	node [ id 29 label "C" ]
	node [ id 30 label "O" ]
	node [ id 31 label "N" ]
	node [ id 32 label "C" ]
	node [ id 33 label "N" ]
	node [ id 34 label "C" ]
	node [ id 35 label "C" ]
	node [ id 36 label "N" ]
	node [ id 37 label "C" ]
	node [ id 38 label "N" ]
	node [ id 39 label "C" ]
	node [ id 40 label "N" ]
	node [ id 41 label "O" ]
	node [ id 42 label "O" ]
	node [ id 43 label "P" ]
	node [ id 44 label "O" ]
	node [ id 45 label "O" ]
	node [ id 46 label "O" ]
	node [ id 47 label "O" ]
	node [ id 48 label "TEST" ]
	node [ id 49 label "H" ]
	node [ id 50 label "H" ]
	node [ id 51 label "H" ]
	node [ id 52 label "H" ]
	node [ id 53 label "H" ]
	node [ id 54 label "H" ]
	node [ id 55 label "H" ]
	node [ id 56 label "H" ]
	node [ id 57 label "H" ]
	node [ id 58 label "H" ]
	node [ id 59 label "H" ]
	node [ id 60 label "H" ]
	node [ id 61 label "H" ]
	node [ id 62 label "H" ]
	node [ id 63 label "H" ]
	node [ id 64 label "H" ]
	node [ id 65 label "H" ]
	node [ id 66 label "H" ]
	node [ id 67 label "H" ]
	node [ id 68 label "H" ]
	node [ id 69 label "H" ]
	node [ id 70 label "H" ]
	node [ id 71 label "H" ]
	node [ id 72 label "H" ]
	node [ id 73 label "H" ]
	node [ id 74 label "H" ]
	node [ id 75 label "H" ]
	node [ id 76 label "H" ]
	node [ id 77 label "H" ]
	node [ id 78 label "H" ]
	node [ id 79 label "H" ]
	node [ id 80 label "H" ]
	node [ id 81 label "H" ]
	node [ id 82 label "H" ]
	node [ id 83 label "H" ]
	edge [ source 1 target 0 label "-" ]
	edge [ source 2 target 1 label "-" ]
	edge [ source 3 target 2 label "-" ]
	edge [ source 5 target 4 label "=" ]
	edge [ source 4 target 3 label "-" ]
	edge [ source 6 target 4 label "-" ]
	edge [ source 7 target 6 label "-" ]
	edge [ source 8 target 7 label "-" ]
	edge [ source 10 target 9 label "=" ]
	edge [ source 9 target 8 label "-" ]
	edge [ source 13 target 12 label "-" ]
	edge [ source 14 target 12 label "-" ]
	edge [ source 12 target 11 label "-" ]
	edge [ source 15 target 12 label "-" ]
	edge [ source 16 target 15 label "-" ]
	edge [ source 18 target 17 label "=" ]
	edge [ source 19 target 17 label "-" ]
	edge [ source 17 target 16 label "-" ]
	edge [ source 20 target 17 label "-" ]
	edge [ source 22 target 21 label "=" ]
	edge [ source 23 target 21 label "-" ]
	edge [ source 21 target 20 label "-" ]
	edge [ source 24 target 21 label "-" ]
	edge [ source 25 target 24 label "-" ]
	edge [ source 26 target 25 label "-" ]
	edge [ source 30 target 26 label "-" ]
	edge [ source 30 target 29 label "-" ]
	edge [ source 29 target 28 label "-" ]
	edge [ source 31 target 29 label "-" ]
	edge [ source 32 target 31 label "-" ]
	edge [ source 33 target 32 label "=" ]
	edge [ source 34 target 33 label "-" ]
	edge [ source 36 target 35 label "-" ]
	edge [ source 37 target 36 label "=" ]
	edge [ source 38 target 37 label "-" ]
	edge [ source 39 target 34 label "-" ]
	edge [ source 39 target 31 label "-" ]
	edge [ source 39 target 38 label "=" ]
	edge [ source 35 target 34 label "=" ]
	edge [ source 40 target 35 label "-" ]
	edge [ source 28 target 27 label "-" ]
	edge [ source 41 target 28 label "-" ]
	edge [ source 27 target 26 label "-" ]
	edge [ source 42 target 27 label "-" ]
	edge [ source 44 target 43 label "=" ]
	edge [ source 45 target 43 label "-" ]
	edge [ source 43 target 42 label "-" ]
	edge [ source 46 target 43 label "-" ]
	edge [ source 11 target 9 label "-" ]
	edge [ source 47 target 11 label "-" ]
	edge [ source 48 target 0 label "-" ]
	edge [ source 49 target 1 label "-" ]
	edge [ source 50 target 1 label "-" ]
	edge [ source 51 target 2 label "-" ]
	edge [ source 52 target 2 label "-" ]
	edge [ source 53 target 3 label "-" ]
	edge [ source 54 target 6 label "-" ]
	edge [ source 55 target 6 label "-" ]
	edge [ source 56 target 7 label "-" ]
	edge [ source 57 target 7 label "-" ]
	edge [ source 58 target 8 label "-" ]
	edge [ source 59 target 11 label "-" ]
	edge [ source 60 target 13 label "-" ]
	edge [ source 61 target 13 label "-" ]
	edge [ source 62 target 13 label "-" ]
	edge [ source 63 target 14 label "-" ]
	edge [ source 64 target 14 label "-" ]
	edge [ source 65 target 14 label "-" ]
	edge [ source 66 target 15 label "-" ]
	edge [ source 67 target 15 label "-" ]
	edge [ source 68 target 19 label "-" ]
	edge [ source 69 target 23 label "-" ]
	edge [ source 70 target 25 label "-" ]
	edge [ source 71 target 25 label "-" ]
	edge [ source 72 target 26 label "-" ]
	edge [ source 73 target 27 label "-" ]
	edge [ source 74 target 28 label "-" ]
	edge [ source 75 target 29 label "-" ]
	edge [ source 76 target 32 label "-" ]
	edge [ source 77 target 37 label "-" ]
	edge [ source 78 target 40 label "-" ]
	edge [ source 79 target 40 label "-" ]
	edge [ source 80 target 41 label "-" ]
	edge [ source 81 target 45 label "-" ]
	edge [ source 82 target 46 label "-" ]
	edge [ source 83 target 47 label "-" ]
]
