rule[
    ruleID "rTCA_activation_ATP_citrate_lyase_01"
    labelType "term"
    left [
        edge [ source 0 target 3 label "-" ]
        edge [ source 0 target 6 label "-" ]
        edge [ source 6 target 7 label "-" ]
    ]
    context [
        node [ id 0 label "C" ]
        node [ id 1 label "C" ]
        node [ id 2 label "O" ]
        node [ id 3 label "C" ]
        node [ id 4 label "H" ]
        node [ id 5 label "H" ]
        node [ id 6 label "O" ]
        node [ id 7 label "H" ]
        node [ id 8 label "_X" ]
        node [ id 9 label "O" ]
        node [ id 10 label "H" ]
        node [ id 11 label "C" ]
        node [ id 12 label "O" ]
        node [ id 13 label "S" ]        
        node [ id 14 label "CoA" ]
        edge [ source 0 target 1 label "-" ]
        edge [ source 1 target 2 label "=" ]
        edge [ source 1 target 9 label "-" ]
        edge [ source 9 target 10 label "-" ]
        edge [ source 0 target 8 label "-" ]
        edge [ source 3 target 4 label "-" ]
        edge [ source 3 target 5 label "-" ]
        edge [ source 3 target 11 label "-" ]
        edge [ source 11 target 12 label "=" ]
        edge [ source 11 target 13 label "-" ]
        edge [ source 13 target 14 label "-" ]
    ]
    right [
        edge [ source 0 target 6 label "=" ]
        edge [ source 7 target 3 label "-" ]
    ]
    constrainLabelAny [
        label "_X"
        labels [ label "C" label "H"]
    ]
]