rule [
    ruleID "rTCA_activation_dikinase_01_1"
    labelType "term"
    left [
        edge [ source 0 target 2 label "=" ]
        edge [ source 0 target 1 label "-" ]
        edge [ source 1 target 6 label "-" ]
        edge [ source 10 target 11 label "-" ]
        edge [ source 12 target 13 label "-" ]
        edge [ source 25 target 27 label "-" ]
    ]
    context [
        node [ id 0 label "C" ]
        node [ id 1 label "C" ]
        node [ id 2 label "O" ]
        node [ id 3 label "C" ]
        node [ id 4 label "H" ]
        node [ id 5 label "_X" ]
        node [ id 6 label "H" ]
        node [ id 7 label "O" ]
        node [ id 8 label "O" ]
        node [ id 9 label "H" ]
        node [ id 10 label "O" ]
        node [ id 11 label "P" ]
        node [ id 12 label "O" ]
        node [ id 13 label "P" ] 
        node [ id 14 label "O" ]
        node [ id 15 label "O" ]
        node [ id 16 label "H" ]
        node [ id 17 label "O" ]
        node [ id 18 label "H" ]
        node [ id 19 label "O" ]
        node [ id 20 label "O" ]
        node [ id 21 label "H" ]
        node [ id 22 label "P" ]
        node [ id 23 label "O" ]
        node [ id 24 label "Ad" ] 
        node [ id 25 label "O" ]
        node [ id 26 label "H" ]
        node [ id 27 label "H" ]       
        edge [ source 0 target 3 label "-" ]
        edge [ source 3 target 8 label "=" ]
        edge [ source 3 target 7 label "-" ]
        edge [ source 7 target 9 label "-" ]
        edge [ source 1 target 4 label "-" ]
        edge [ source 1 target 5 label "-" ]
        edge [ source 11 target 12 label "-" ]     
        edge [ source 13 target 14 label "=" ]
        edge [ source 13 target 15 label "-" ]
        edge [ source 15 target 16 label "-" ]
        edge [ source 13 target 17 label "-" ]
        edge [ source 17 target 18 label "-" ]
        edge [ source 11 target 19 label "=" ]
        edge [ source 11 target 20 label "-" ]
        edge [ source 20 target 21 label "-" ]
        edge [ source 10 target 22 label "-" ]
        edge [ source 22 target 23 label "-" ]
        edge [ source 23 target 24 label "-" ]
        edge [ source 25 target 26 label "-" ]                 
    ]
    right [
        edge [ source 0 target 2 label "-" ]
        edge [ source 0 target 1 label "=" ]
        edge [ source 2 target 13 label "-" ]
        edge [ source 12 target 6 label "-" ]
        edge [ source 11 target 25 label "-" ]
        edge [ source 10 target 27 label "-" ]
    ]
    constrainLabelAny [
        label "_X"
        labels [ label "H" label "C" ]        
    ]
]